"""empty message

Revision ID: 382270a349cd
Revises: eb98b0170c0f
Create Date: 2023-03-10 18:58:25.640543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382270a349cd'
down_revision = 'eb98b0170c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
