"""empty message

Revision ID: 7e0dce936ba9
Revises: e7ab9bf76eda
Create Date: 2023-04-01 12:31:26.199273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0dce936ba9'
down_revision = 'e7ab9bf76eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(scale=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Numeric(scale=1),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    # ### end Alembic commands ###
